# name: poetry21
channels:
  - defaults
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python=3.8
  - nodejs
  - jedi==0.17.2
  - jupyterlab>=3.0
  - flake8
  - pylint
  - pip
  - sentencepiece
  - numpy
  - transformers #==4.0.1
  - tokenizers
  - nlp
  - psutil
  # - pytorch::pytorch
  # - pytorch::torchvision
  # - pytorch::torchaudio
  # - pytorch::cpuonly
  - pip:
    - datasets
  #   - tokenizers==0.10.0
